In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10, (3,4))
arr

array([[5, 5, 7, 3],
       [7, 3, 8, 8],
       [4, 9, 5, 3]])

In [3]:
arr.reshape(4,3)

array([[5, 5, 7],
       [3, 7, 3],
       [8, 8, 4],
       [9, 5, 3]])

In [4]:
arr.reshape(6,2)

array([[5, 5],
       [7, 3],
       [7, 3],
       [8, 8],
       [4, 9],
       [5, 3]])

In [9]:
# arr.reshape(2,6) #
arr.reshape(2,-1656)

array([[5, 5, 7, 3, 7, 3],
       [8, 8, 4, 9, 5, 3]])

In [10]:
arr.T

array([[5, 7, 4],
       [5, 3, 9],
       [7, 8, 5],
       [3, 8, 3]])

In [11]:
arr

array([[5, 5, 7, 3],
       [7, 3, 8, 8],
       [4, 9, 5, 3]])

In [12]:
arr.flatten()

array([5, 5, 7, 3, 7, 3, 8, 8, 4, 9, 5, 3])

In [13]:
# Now

In [25]:
arr1=np.array([1,2,3,4]) # agar do bracket hota toh 2 dimension hota 
arr1

array([1, 2, 3, 4])

In [26]:
arr1.ndim

1

In [31]:
np.expand_dims(arr1,axis=1) # axis 1 yaani col 1

array([[1],
       [2],
       [3],
       [4]])

In [32]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [33]:
# Now

In [34]:
arr

array([[5, 5, 7, 3],
       [7, 3, 8, 8],
       [4, 9, 5, 3]])

In [36]:
np.squeeze(arr)  # as it is

array([[5, 5, 7, 3],
       [7, 3, 8, 8],
       [4, 9, 5, 3]])

In [40]:
data=np.array([ [1],[2],[3],[4] ])
data

array([[1],
       [2],
       [3],
       [4]])

In [42]:
data.squeeze()

array([1, 2, 3, 4])

In [46]:
# Now

In [47]:
arr1

array([1, 2, 3, 4])

In [49]:
np.roll(arr1,shift=1)

array([4, 1, 2, 3])

In [50]:
np.roll(arr1,shift=3)

array([2, 3, 4, 1])

In [51]:
np.repeat(arr1,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [53]:
np.diag(arr1) # jo element taha 1,2,3,4 wo diagonally aa gaya

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
# Binary operation in numpy

In [55]:
arr1=np.random.randint(1,10, (3,4))
arr1

array([[2, 1, 8, 7],
       [2, 3, 2, 1],
       [1, 1, 1, 4]])

In [57]:
arr2=np.random.randint(1,10, (3,4) )
arr2

array([[9, 3, 5, 5],
       [1, 4, 9, 2],
       [2, 6, 4, 2]])

In [58]:
arr1 + arr2

array([[11,  4, 13, 12],
       [ 3,  7, 11,  3],
       [ 3,  7,  5,  6]])

In [59]:
arr1 - arr2

array([[-7, -2,  3,  2],
       [ 1, -1, -7, -1],
       [-1, -5, -3,  2]])

In [60]:
arr1 / arr2

array([[0.22222222, 0.33333333, 1.6       , 1.4       ],
       [2.        , 0.75      , 0.22222222, 0.5       ],
       [0.5       , 0.16666667, 0.25      , 2.        ]])

In [61]:
arr1 * arr2

array([[18,  3, 40, 35],
       [ 2, 12, 18,  2],
       [ 2,  6,  4,  8]])

In [62]:
arr1 ** arr2

array([[  512,     1, 32768, 16807],
       [    2,    81,   512,     1],
       [    1,     1,     1,    16]])

In [63]:
arr1 & arr2

array([[0, 1, 0, 5],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
arr1 | arr2

array([[11,  3, 13,  7],
       [ 3,  7, 11,  3],
       [ 3,  7,  5,  6]])

In [65]:
-arr1

array([[-2, -1, -8, -7],
       [-2, -3, -2, -1],
       [-1, -1, -1, -4]])

In [66]:
arr1^arr2

array([[11,  2, 13,  2],
       [ 3,  7, 11,  3],
       [ 3,  7,  5,  6]])

In [67]:
# Numpy string

In [70]:
name=['Amar', 'kumar' ] 
name

['Amar', 'kumar']

In [71]:
np.char.capitalize(name)

array(['Amar', 'Kumar'], dtype='<U5')

In [74]:
np.char.upper(name)

array(['AMAR', 'KUMAR'], dtype='<U5')

In [76]:
np.char.isalpha(name)

array([ True,  True])

In [78]:
np.char.title(name)

array(['Amar', 'Kumar'], dtype='<U5')

In [79]:
# Now mathematical operation

In [81]:
arr1

array([[2, 1, 8, 7],
       [2, 3, 2, 1],
       [1, 1, 1, 4]])

In [82]:
np.sin(arr1)

array([[ 0.90929743,  0.84147098,  0.98935825,  0.6569866 ],
       [ 0.90929743,  0.14112001,  0.90929743,  0.84147098],
       [ 0.84147098,  0.84147098,  0.84147098, -0.7568025 ]])

In [83]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.14550003,  0.75390225],
       [-0.41614684, -0.9899925 , -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231, -0.65364362]])

In [84]:
np.tan(arr)

array([[-3.38051501, -3.38051501,  0.87144798, -0.14254654],
       [ 0.87144798, -0.14254654, -6.79971146, -6.79971146],
       [ 1.15782128, -0.45231566, -3.38051501, -0.14254654]])

In [85]:
np.tanh(arr)

array([[0.9999092 , 0.9999092 , 0.99999834, 0.99505475],
       [0.99999834, 0.99505475, 0.99999977, 0.99999977],
       [0.9993293 , 0.99999997, 0.9999092 , 0.99505475]])

In [86]:
np.sinh(arr)

array([[  74.20321058,   74.20321058,  548.31612327,   10.01787493],
       [ 548.31612327,   10.01787493, 1490.47882579, 1490.47882579],
       [  27.2899172 , 4051.54190208,   74.20321058,   10.01787493]])

In [87]:
np.max(arr)

9

In [88]:
np.min(arr)

3

In [89]:
np.sqrt(arr)

array([[2.23606798, 2.23606798, 2.64575131, 1.73205081],
       [2.64575131, 1.73205081, 2.82842712, 2.82842712],
       [2.        , 3.        , 2.23606798, 1.73205081]])

In [91]:
np.power(arr,2)

array([[25, 25, 49,  9],
       [49,  9, 64, 64],
       [16, 81, 25,  9]])

In [92]:
np.mean(arr)

5.583333333333333

In [93]:
np.median(arr)

5.0

In [96]:
np.mod(arr,2)

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [97]:
np.std(arr)

2.0598678490513795