In [2]:
# Numerical Python called Numpy is a library in python for mathematical opeartions based on array and index
# like Matlab

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
ar=np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar) # nd array means nth dimensional array 

numpy.ndarray

In [6]:
ar1=np.array( [ [1,2] , [5,4] ] )  # 2d array means jitna square bracket utna dimension
ar1

array([[1, 2],
       [5, 4]])

In [7]:
type(ar1)

numpy.ndarray

In [8]:
l

[1, 2, 3, 4]

In [9]:
np.asarray(l) # convert karta 2d array ko 1d mein 

array([1, 2, 3, 4])

In [10]:
print("ar = ",np.asarray(ar)) 
print("ar1 = ",end=" ")   # doubt kaha convert kiya ar1 (2d ko 1d mein)
np.asarray(ar1)           # doubt solved asarray() list ko array mein convert karta bhai

ar =  [1 2 3 4]
ar1 =  

array([[1, 2],
       [5, 4]])

In [11]:
# ye dekho
print(l)
l1=np.asarray(l) # covnert list into array  # doubt np.array bhi toh wahi kaam kar raha list ko array mein convert kar raha
                                            # solved np.array,np.asarray() , ya np.asanyarray() all are same whose work is to convert list into array

[1, 2, 3, 4]


In [12]:
type(l1)

numpy.ndarray

In [13]:
l2=np.asanyarray(l)

In [14]:
type(l)

list

In [15]:
type(l2)

numpy.ndarray

In [16]:
# convert list into matrix

In [17]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [18]:
type(b)

numpy.matrix

In [19]:
# Now convert matrix into array

In [20]:
b1=np.asarray(b)  # not convert matrix into array still because matrix bhi array ka hi form hai[asarray list ko array mein convert karta but jo already arrray hai usko toh array mein hi convert  kareegea  na ]
b1

array([[1, 2, 3, 4]])

In [21]:
# type(np.asarray(b)) # 
type(b1)  # bhale matrix se array mein convert kiya but type array hi hai [matrix likha raha tha upar dekho line 55]

numpy.ndarray

In [22]:
# NOw

In [23]:
a=np.array(l)
a

array([1, 2, 3, 4])

In [24]:
c=a

In [25]:
c

array([1, 2, 3, 4])

In [26]:
c[0]=101

In [27]:
c

array([101,   2,   3,   4])

In [28]:
a  # we didn't change in a but how a changes by changeing c becasue we take its reference(pointer) same address par hai wo
        # its  called "swallow copy"

array([101,   2,   3,   4])

In [29]:
a[2]=5 # a ke 2nd index par 5 but c mein bhi changes hoga because of swallow copy
c

array([101,   2,   5,   4])

In [30]:
# now deep copy

In [31]:
d=np.copy(a)
d

array([101,   2,   5,   4])

In [32]:
a[1]=88
a

array([101,  88,   5,   4])

In [33]:
d  # d ke 1 index par 88 nahi aaya because ye alag location par array banaya it's called deep copy

array([101,   2,   5,   4])

In [34]:
# Now np.fromfunction()

In [35]:
np.fromfunction(lambda i,j:   i==j, (3,3) )

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j: i+j,  (3,3) )

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [37]:
# Now fromiter() : loop se array bana raha

In [38]:
iterable = (i*i for i in range(5) )

In [39]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [40]:
# fromstring : string se array bana raha 

In [41]:
np.fromstring('1 2 3 4 5',  dtype=int, sep=' ') # no need to write , after each number like 1 2 3 4 5

array([1, 2, 3, 4, 5])

In [42]:
np.fromstring('1,2,3,4,5' , dtype=int, sep= ',') # separate by , 

array([1, 2, 3, 4, 5])

In [43]:
# Now

In [44]:
l=[1,2,3,4,5]

In [45]:
ar=np.array(l)
ar

array([1, 2, 3, 4, 5])

In [46]:
ar.ndim

1

In [47]:
# Now 
ar2=np.array( [ [1,2,3,4],[2,3,4,5] ] )
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [48]:
ar2.ndim

2

In [49]:
ar.size

5

In [50]:
ar2.size

8

In [51]:
ar.shape # 5 element 

(5,)

In [52]:
ar2.shape # 2 row 4 column

(2, 4)

In [53]:
ar.dtype

dtype('int64')

In [54]:
ar1.dtype

dtype('int64')

In [55]:
# Now

In [56]:
# ar22=np.asarray([ [1.4,5,6] , [2,3,4] ] ) # both list or 
ar22=np.asarray([ (1.4,5,6), (2,3,4) ] ) # tuple inside list
ar22

array([[1.4, 5. , 6. ],
       [2. , 3. , 4. ]])

In [57]:
ar22.dtype # ek float raha 1.4 but uske karan sabko floating point number bana diya automatically

dtype('float64')

In [58]:
# Now

In [59]:
range(5)

range(0, 5)

In [60]:
print(list(range(5)))
list(range(2,9))

[0, 1, 2, 3, 4]


[2, 3, 4, 5, 6, 7, 8]

In [61]:
list(range(1.4, 5.2) )

TypeError: 'float' object cannot be interpreted as an integer

In [62]:
np.arange(1.4,5.4) # by default 1 jump

array([1.4, 2.4, 3.4, 4.4])

In [63]:
np.arange(1.4,5.8,.5) # jum 0.2

array([1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4])

In [64]:
list(np.arange(1.4,5.8,.5) ) # jum 0.2)

[1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4]

In [65]:
print(np.linspace(1,5, 10)) # 1 se 5 tak number aur usko 10 bhaag karo
np.linspace(1,10,10)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [69]:
ar4=np.zeros((3,4,5,2))
ar4

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
       

In [70]:
ar4.ndim

4

In [71]:
np.ones(4)

array([1., 1., 1., 1.])

In [72]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
on=np.ones((2,3,4)) # 3 row 4 column ke 2 matrix bana denge
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [74]:
on+4  

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [75]:
on*8.8

array([[[8.8, 8.8, 8.8, 8.8],
        [8.8, 8.8, 8.8, 8.8],
        [8.8, 8.8, 8.8, 8.8]],

       [[8.8, 8.8, 8.8, 8.8],
        [8.8, 8.8, 8.8, 8.8],
        [8.8, 8.8, 8.8, 8.8]]])

In [76]:
np.empty((4,4)) # random entry

array([[4.66627148e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

In [77]:
np.eye(4) # diagonal matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
np.linspace( 3 ,21,7) # 1 to 8 tak ko 10 se bhag kar do

array([ 3.,  6.,  9., 12., 15., 18., 21.])

In [79]:
np.logspace(1,1000, 10, base=10)

/opt/conda/lib/python3.10/site-packages/numpy/core/function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.e+001, 1.e+112, 1.e+223,     inf,     inf,     inf,     inf,
           inf,     inf,     inf])

In [80]:
# Now

In [81]:
np.random.rand(3,4) # mean=0 and std=1 

array([[0.81773208, 0.05349626, 0.32476068, 0.23542595],
       [0.19149989, 0.90342908, 0.75351745, 0.63763618],
       [0.73017501, 0.73914288, 0.36223617, 0.6605836 ]])

In [82]:
arr=np.random.randn(3,4)
arr

array([[ 1.87449075,  1.59437558, -1.34264988, -1.5992608 ],
       [-1.16259831,  1.68420446, -0.46627624, -0.20860423],
       [-2.29947896,  0.9363924 , -0.51142143,  0.01488269]])

In [83]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0  1.874491  1.594376 -1.342650 -1.599261
1 -1.162598  1.684204 -0.466276 -0.208604
2 -2.299479  0.936392 -0.511421  0.014883

In [84]:
np.random.randint(1,10, 4) # 1 se 10 tak random data of size 4 

array([8, 5, 1, 4])

In [85]:
np.random.randint(1,1000, (300,400) ) # 1 se 1000 tak and size 3 row 4 column

array([[282, 745, 284, ..., 542, 421, 636],
       [566, 268, 436, ...,  71, 149, 246],
       [521, 899,  54, ..., 545, 350, 786],
       ...,
       [852, 958,  65, ..., 990,  93, 968],
       [108,  82, 938, ..., 943,   4, 953],
       [840, 509,   9, ..., 271, 942, 537]])

In [86]:
pd.DataFrame(np.random.randint(1,1000, (300,400) ) ) # 1 se 1000 tak and size 3 row 4 column

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0    179    7  490  857  620  200  982  168  148  909  ...  949  926  444   
1    478  335  729  514  136   15  725  726  634  929  ...  319  990  957   
2    500  122  166  522  959  321  684  787  132  376  ...    9  671   86   
3    942   65  962  193   19   18  843  509  351  697  ...  400  653  903   
4    502  702  476  180  488  521  439  382  158  101  ...  518  296  899   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   19  718   46  327  286  135  122  955  784  890  ...  703  290  517   
296  381  755  414  212  587   68  926  454  915  720  ...   95  830  768   
297  131  709  820  890  115  192  251  749  820  388  ...  882  563  695   
298  513  716  606  939  710  141  354  965   50   91  ...  985  607  506   
299  397  536  768  959  440  757  676  356  974  286  ...  228  197  211   

     393  394  395  396  397  398  399  
0    529  337  576  884  754   93  282  
1    462  311  488   27   51  288  455  
2    819  802  737  595   43  369  987  
3    626   73  922  797  853  426    1  
4    710  810  355  222  245  105  933  
..   ...  ...  ...  ...  ...  ...  ...  
295  689  692  308  731  373  406  464  
296  243  936   55  577  559  803  283  
297  769   27  485  817  669  244  876  
298  764  309  527  534  799  427  365  
299  164  996  990  656  125  346  916  

[300 rows x 400 columns]

In [87]:
# Now convert it into csv and store in file
pd.DataFrame(np.random.randint(1,1000, (300,400) ) ). to_csv("test.csv") # 1 se 1000 tak and size 3 row 4 column

In [88]:
# Now

In [89]:
arr=np.random.rand(3,4)
arr

array([[0.5794839 , 0.39683356, 0.01163916, 0.7519103 ],
       [0.46939133, 0.52911108, 0.75754097, 0.45643457],
       [0.39251344, 0.53909423, 0.68734967, 0.46756806]])

In [90]:
arr.reshape(4,3)

array([[0.5794839 , 0.39683356, 0.01163916],
       [0.7519103 , 0.46939133, 0.52911108],
       [0.75754097, 0.45643457, 0.39251344],
       [0.53909423, 0.68734967, 0.46756806]])

In [91]:
arr.reshape(6,2)

array([[0.5794839 , 0.39683356],
       [0.01163916, 0.7519103 ],
       [0.46939133, 0.52911108],
       [0.75754097, 0.45643457],
       [0.39251344, 0.53909423],
       [0.68734967, 0.46756806]])

In [92]:
arr.reshape(6,4)

ValueError: cannot reshape array of size 12 into shape (6,4)

In [93]:
arr.reshape(6,-1)

array([[0.5794839 , 0.39683356],
       [0.01163916, 0.7519103 ],
       [0.46939133, 0.52911108],
       [0.75754097, 0.45643457],
       [0.39251344, 0.53909423],
       [0.68734967, 0.46756806]])

In [94]:
arr1=arr.reshape(6,-2343434) # by default samajh gaya ki pehla 6 hai toh dusra 2 hi hoga
arr1                            # but ye sirf -ve number ke liye work karta not +ve or float number 

array([[0.5794839 , 0.39683356],
       [0.01163916, 0.7519103 ],
       [0.46939133, 0.52911108],
       [0.75754097, 0.45643457],
       [0.39251344, 0.53909423],
       [0.68734967, 0.46756806]])

In [95]:
arr.reshape(3,-2555) # 3 row toh 4 column hoga bydefault samajh gaya

array([[0.5794839 , 0.39683356, 0.01163916, 0.7519103 ],
       [0.46939133, 0.52911108, 0.75754097, 0.45643457],
       [0.39251344, 0.53909423, 0.68734967, 0.46756806]])

In [96]:
arr1

array([[0.5794839 , 0.39683356],
       [0.01163916, 0.7519103 ],
       [0.46939133, 0.52911108],
       [0.75754097, 0.45643457],
       [0.39251344, 0.53909423],
       [0.68734967, 0.46756806]])

In [97]:
arr1[1][1]

0.7519102994247763

In [100]:
print(arr1[2:5] [1] ) #  Not work    # 2,3,4 row ke 1st column ko nikalo 
arr1[2:5,1] # correct output

[0.75754097 0.45643457]


array([0.52911108, 0.45643457, 0.53909423])

In [101]:
# Now

In [102]:
arr=np.random.randint(30,99,(5,5))
arr

array([[32, 34, 74, 61, 70],
       [71, 30, 37, 83, 90],
       [58, 77, 57, 90, 39],
       [53, 60, 82, 51, 78],
       [73, 87, 76, 62, 79]])

In [103]:
arr>50

array([[False, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [104]:
arr[arr>50]

array([74, 61, 70, 71, 83, 90, 58, 77, 57, 90, 53, 60, 82, 51, 78, 73, 87,
       76, 62, 79])

In [105]:
arr

array([[32, 34, 74, 61, 70],
       [71, 30, 37, 83, 90],
       [58, 77, 57, 90, 39],
       [53, 60, 82, 51, 78],
       [73, 87, 76, 62, 79]])

In [110]:
# 2,3 row and 1,2 column
arr[2:4,1:3]

array([[77, 57],
       [60, 82]])

In [111]:
arr[2:4,[1,2] ]

array([[77, 57],
       [60, 82]])

In [112]:
arr[0][0] = 555
arr

array([[555,  34,  74,  61,  70],
       [ 71,  30,  37,  83,  90],
       [ 58,  77,  57,  90,  39],
       [ 53,  60,  82,  51,  78],
       [ 73,  87,  76,  62,  79]])

In [113]:
# NOw

In [127]:
arr1=np.random.randint(1,10, (3,3) ) 
arr1

array([[5, 8, 3],
       [4, 1, 3],
       [1, 6, 4]])

In [128]:
arr2=np.random.randint(1,10,(3,3))
arr2

array([[1, 7, 6],
       [7, 3, 6],
       [6, 6, 7]])

In [129]:
arr1+arr2

array([[ 6, 15,  9],
       [11,  4,  9],
       [ 7, 12, 11]])

In [130]:
arr1-arr2

array([[ 4,  1, -3],
       [-3, -2, -3],
       [-5,  0, -3]])

In [131]:
arr1/arr2

array([[5.        , 1.14285714, 0.5       ],
       [0.57142857, 0.33333333, 0.5       ],
       [0.16666667, 1.        , 0.57142857]])

In [132]:
arr1*arr2    # this gives element multiplication not matrix multiplication

array([[ 5, 56, 18],
       [28,  3, 18],
       [ 6, 36, 28]])

In [133]:
arr1@arr2

array([[79, 77, 99],
       [29, 49, 51],
       [67, 49, 70]])

In [135]:
arr1+1000

array([[1005, 1008, 1003],
       [1004, 1001, 1003],
       [1001, 1006, 1004]])

In [136]:
arr1/0

/tmp/ipykernel_84/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [137]:
arr1**2

array([[25, 64,  9],
       [16,  1,  9],
       [ 1, 36, 16]])

In [138]:
# Now Broadcasting

In [150]:
arr= np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
row=[1,2,3,4]
row

[1, 2, 3, 4]

In [152]:
arr+row # when we added arr +1000 it added 1000 to all elements in the matrix 
                    # but this time it added 1,2,3,4 row wise 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
# Now  we want to add it columnn wise

In [161]:
col=np.array([[1,2,3,4]])
col

array([[1, 2, 3, 4]])

In [168]:
# col.transpose() # same
col=col.T

In [169]:
arr+col

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [172]:
arr1=np.random.randint(1,4, (3,4))
arr1

array([[1, 2, 2, 3],
       [3, 2, 3, 3],
       [3, 1, 1, 3]])

In [174]:
np.sum(arr1)

27

In [177]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 1.73205081, 1.73205081],
       [1.73205081, 1.        , 1.        , 1.73205081]])

In [178]:
np.exp(arr1)

array([[ 2.71828183,  7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692,  7.3890561 , 20.08553692, 20.08553692],
       [20.08553692,  2.71828183,  2.71828183, 20.08553692]])

In [179]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.        , 0.        , 0.47712125]])

In [180]:
np.amax(arr1)

3