In [13]:
import numpy as ny

In [14]:
arr=ny.array([2,3,4,3,5,3,3,4,3333,33,34])
arr

array([   2,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [15]:
ny.sort(arr)

array([   2,    3,    3,    3,    3,    4,    4,    5,   33,   34, 3333])

In [16]:
ny.searchsorted(arr,3) # if available give index

1

In [17]:
ny.searchsorted(arr,9) # if not available give its index where to put

8

In [18]:
# Now

In [20]:
arr1=ny.array([0,0,2,3,0,2,0,0] )
arr1

array([0, 0, 2, 3, 0, 2, 0, 0])

In [22]:
ny.count_nonzero(arr1)

3

In [27]:
ny.where(arr1==2)

(array([2, 5]),)

In [28]:
ny.where(arr1>1)

(array([2, 3, 5]),)

In [29]:
ny.extract(arr>3, arr)

array([   4,    5,    4, 3333,   33,   34])

In [30]:
# Now Byteswapping

In [31]:
arr

array([   2,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [34]:
arr.byteswap()

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        216172782113783808,  360287970189639680,  216172782113783808,
        216172782113783808,  288230376151711744,  363947144886878208,
       2377900603251621888, 2449958197289549824])

In [35]:
# Now  copies and views

In [36]:
arr

array([   2,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [39]:
a=ny.copy(arr) # dcopy means agar a mein changes hoga toh arr mein changes nahi hoga
a

array([   2,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [43]:
b=arr.view()   # or b=arr 

In [44]:
b

array([   2,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [45]:
arr

array([   2,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [46]:
b[0]=88
b

array([  88,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [47]:
arr

array([  88,    3,    4,    3,    5,    3,    3,    4, 3333,   33,   34])

In [49]:
# ****

In [50]:
import numpy.matlib as nm

In [51]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [52]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [54]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [57]:
#Linear Algebra

In [65]:
arr1=ny.random.randint( [1,2] , [2,3] )
arr1

array([1, 2])

In [68]:
test=ny.random.randint( [[1,2] , [2,3]] )
test

array([[0, 0],
       [0, 1]])

In [70]:
arr1=ny.random.randint([[2,3],[4,5]] )
arr1

array([[1, 1],
       [2, 4]])

In [72]:
arr2=ny.random.randint([[5,3],[2,5]] )
arr2

array([[4, 2],
       [1, 2]])

In [75]:
ny.dot(arr1,arr2) # matrix multiplication

array([[ 5,  4],
       [12, 12]])

In [76]:
arr1@arr2

array([[ 5,  4],
       [12, 12]])